#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Symfony\Component\Console\Application('ITDC Fourstead', '3.0.1');

$app->add(new ITDCMS\Fourstead\MakeCommand);

$app->run();
